name: WorkflowB

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  BJob1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: B Step 1
        run: echo B Step 1
      #reusable workflows should be referenced at the top-level `jobs.*.uses' key, not within steps  
      #- name: CallA
      #  uses: megamanics/workflows/.github/workflows/A.yml@main
  BJob2:
    needs: BJob1
    uses: megamanics/workflows/.github/workflows/A.yml@main
  BJob3:
    uses: devops-testbed/intake/.github/workflows/main.yml@main
