name: WorkflowC

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  CJob1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: C Step 1
        run: echo C Step 1
      #reusable workflows should be referenced at the top-level `jobs.*.uses' key, not within steps  
      #- name: CallA
      #  uses: megamanics/workflows/.github/workflows/A.yml@main
  CJob2:
    needs: CJob1
    uses: megamanics/workflows/.github/workflows/B.yml@main
  #
#error parsing called workflow "devops-testbed/intake/.github/workflows/main.yml@main": 
#error parsing called workflow "megamanics/workflows/.github/workflows/C.yml@main": error parsing called workflow "megamanics/workflows/.github/workflows/B.yml@main": job "BJob2" calls workflow "megamanics/workflows/.github/workflows/A.yml@main", but doing so would exceed the limit on called workflow depth of 3
#  CJob3:
#    uses: devops-testbed/intake/.github/workflows/main.yml@main
