name: debug

on:
  workflow_call:
  workflow_dispatch:

jobs:
  addEventArtifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello > event.json
      - uses: actions/upload-artifact@v3
        with:
          path: event.json
      - run: env > env.txt
      - uses: actions/upload-artifact@v3
        with:
          path: env.txt
      - run: echo ${RUNNER_DEBUG} 
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
