name: debug

on:
  workflow_call:
  workflow_dispatch:

jobs:
  addEventArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event context
        env:
          GH_EVENT: ${{ toJson(github.event) }}
        run: echo "$GH_EVENT" > event.json
      - uses: actions/upload-artifact@v3
        with:
          path: event.json
      - run: env | sort > env.txt
      - uses: actions/upload-artifact@v3
        with:
          path: env.txt
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
